config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  devise_for :users
  resources :users
  #resources :products

  #yanked code below from nov122015 project
  #resources :orders
  #resources :line_items
  #resources :carts
  #root to: 'visitors#index'
  #devise_for :users
  #resources :users
  #resources :payments
  #add route for products/display_item
  resources :products do
    collection do
      match 'display', :via => [:get, :post]
    end
  end
  resources :line_items
  resources :carts
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :name, :description, :image_url, uniqueness: true

  has_many :line_items
  before_destroy :ensure_not_referenced_by_any_line_item
  
  private 
  #ensure no line items reference this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items Present')
        return false
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart

  def new
    @cart = Cart.new
  end

  def index
    #@line_items = Cart.find(params[:id]).line_items
  end

  def create
    @cart = Cart.new(cart_params)
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: "Cart was successfully created" }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end
 
  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Cart was successfully destroyed'}
      format.json { head :no_content }
    end
  end

  def destroy_individual_item
    redirect_to root_path
  end

  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: "Cart was successfully updated" }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def show
  end

  private

  def invalid_cart
    logger.error "Attempt to access invalid cart"
    redirect_to root_path, notice: 'Invalid cart'
  end

  def set_cart
    @cart = Cart.find(params[:id])
  end

  def cart_params
    params[:cart]
  end
end

app/controllers/concerns/current_cart.rb
module CurrentCart
  extend ActiveSupport::Concern
  
  private

  def set_cart
    @cart = Cart.find(session[:cart_id])
  rescue ActiveRecord::RecordNotFound
    @cart = Cart.create
    session[:cart_id] = @cart.id
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  def index
    @line_items = LineItem.all
  end

  def new
    @line_item = LineItem.new
  end

  def show
  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
   # @line_item = @cart.line_items.build(product: product)
    respond_to do |format|
      if @line_item.save
        format.html {redirect_to @line_item.cart, notice: 'Line item was successfully created'}
        format.json {render action: 'show', status: :created, location: @line_item}
      else
        format.html {render action: 'new'}
        format.json {render json: @line_item.errors, status: :unprocessable_entity}
      end
    end
  end
  
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was destroyed'}
      format.json { head :no_content }
    end
  end

  def destroy_individual_item
    redirect_to root_path
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.'}
        format.json { render :show, status: :ok, location: @line_item}
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  private

    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    def line_item_params
      params.require(:line_item).permit(:product_id, :cart_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, :except => [:display]
  before_action :admin_only, :except => [:display]
  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Successfully Added A New Product"
      redirect_to root_path
    else
      render :new
    end
  end

  def index
    @products = Product.all
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    flash[:success] = "Product has been successfully destroyed"
    redirect_to root_path
  end

  def show
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "Successful Product Update"
      redirect_to root_path
    else
      render 'edit'
    end
  end

  def display
    @product = Product.find(params[:content])
  end

  private
  
    def product_params
      params.require(:product).permit(:name, :description, :price, :image_url)
    end
    
    def admin_only
      unless current_user.admin?
        redirect_to :back, :alert => "Access denied."
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @products = Product.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/carts/index.html.erb
<h2>Your Cart Contents</h2>

<%@cart.line_items.each do |item|%>
  <%=item.name%>
<%end%>

app/views/carts/show.html.erb
<%if notice%>
<p id="notice"><%=notice%></p>
<%end%>

<h2>Your Shopping Cart</h2>
<ul>
  <%@cart.line_items.each do |item|%>
    <li><%=item.quantity%>&times; <%=item.product.name%></li>
  <%end%>
</ul>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to 'My Cart', carts_path%></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%=link_to 'New Product', new_product_path%></li>
    <li><%=link_to 'Edit or Delete Existing Product', products_path%></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Signup Download" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Signup Download" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<center><h3>About Us</h3></center>
<center><p>
Welcome to Larsen & McDermott Enterprises online store. We are a software development company that specializes in building and selling digital products.
</p></center>

app/views/products/create.html.erb
<h3>This is the create template for products</h3>

app/views/products/display.html.erb
<h3>Product Details</h3>


<b>Product Name: </b><%=@product.name%><br/>
<b>Product Description: </b><%=@product.description%><br/>
<b>Product Price(USD): </b>$<%=@product.price%><br/><br/>

<%=button_to "Add To Cart", line_items_path(product_id: @product), class: "btn btn-primary"%>

app/views/products/edit.html.erb
<h2>Edit This Product</h2>

<%=form_for(@product) do |product|%>
  <%if @product.errors.any?%>
    <div id="error_explanation">
      <h2><%=pluralize(@product.errors.count, "error")%> prohibited this product from being saved: </h2>
      <ul>
      <%@product.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
      <%end%>
      </ul>
    </div>
  <%end%>

  <div class="field">
    <%=product.label :name%>
    <%=product.text_field :name%>
  </div>

  <div class="field">
    <%=product.label :description%>
    <%=product.text_field :description%>
  </div>

  <div class="field">
    <%=product.label :price%>
    <%=product.text_field :price%>
  </div>

  <div class="field">
    <%=product.label :image_url%>
    <%=product.text_field :image_url%>
  </div>

  <div class="actions">
    <%=product.submit "Submit Updated Product"%>
  </div>
<%end%>

app/views/products/index.html.erb
<h1>All Products</h1>

<%@products.each do |product|%>
  <h4>Product <%=product.id%></h4>
  <%=product.name%><br/>
  <%=product.description%><br/>
  <%=product.price%><br/>
  <%=product.image_url%><br/>
  <%=link_to "Edit Product", edit_product_path(product)%><br/>
  <%=link_to "Delete Product", product, method: :delete, data: {confirm: 'Are you sure you want to delete that product?'}%>
  <br/>
<%end%>

app/views/products/new.html.erb
<h1>Create a New Product</h1>

<%=form_for(@product) do |product|%>
  <%if @product.errors.any?%>
    <div id="error_explanation">
      <h2><%=pluralize(@product.errors.count, "error")%> prohibited this product from being saved: </h2>
      <ul>
      <%@product.errors.full_messages.each do |msg|%>
        <li><%=msg%></li>
      <%end%>
      </ul>
    </div>
  <%end%>

  <div class="field">
    <%=product.label :name%>
    <%=product.text_field :name%>
  </div>

  <div class="field">
    <%=product.label :description%>
    <%=product.text_field :description%>
  </div>

  <div class="field">
    <%=product.label :price%>
    <%=product.text_field :price%>
  </div>

  <div class="field">
    <%=product.label :image_url%>
    <%=product.text_field :image_url%>
  </div>

  <div class="actions">
    <%=product.submit "Submit New Product"%>
  </div>
<%end%>

app/views/products/update.html.erb
<h2>You Have Updated the Product</h2>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <p class="lead">Larsen & McDermott Enterprises, LLC</p>
            <%if !user_signed_in?%>
              <div><%=link_to 'Sign Up For a Free Game Download', new_user_registration_path, :class => 'btn btn-primary btn-large' %></div><br/>
            <%end%>
        </div>
        <div class="col-md-9">
            <div class="row carousel-holder">
                <div class="col-md-12">
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner">
                            <div class="item active">
                                <img class="new-slide-image" src="<%=image_path("windows.jpg")%>" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image-2" src="<%=image_path("windows.jpg")%>" alt="">
                            </div>
                            <div class="item">
                                <img class="slide-image-3" src="<%=image_path("windows.jpg")%>" alt="">
                            </div>
                        </div>
                        <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left"></span>
                        </a>
                        <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right"></span>
                        </a>
                    </div>
                </div>
            </div><br/>
            <div class="row">
                <%@products.each do |product|%>
                  <div class="col-sm-4 col-lg-4 col-md-4">
                    <div class="thumbnail">
                        <img src="http://placehold.it/320x150" alt="">
                        <div class="caption">
                            <h4 class="pull-right">$<%=product.price%></h4>
                            <h4><%= link_to raw("#{product.name}"), :controller => 'products', :action => 'display', :content => product %>
                            </h4>
                            <p><%=product.description%></p>
                        </div>
                    </div>
                  </div>
                <%end%>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /.container -->
<div class="container">
    <hr>
    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Larsen & McDermott Enterprises, LLC 2015</p>
            </div>
        </div>
    </footer>
   
</div>
<!-- /.container -->